/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemapedidos;

import java.awt.HeadlessException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.converter.LocalDateTimeStringConverter;
import javax.swing.ComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;


public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    
     ProdutoTabela tabela = new ProdutoTabela(); // inicializa a tabela
    
    public Janela() {
        
        initComponents();
        
        tabelaPedidos.setModel(tabela);
        txtPedido.setEnabled(false);
        txtCod.setEnabled(false);
        txtData.setEnabled(false);
        txtDesProduto.setEnabled(false);
        txtQuantidade.setEnabled(false);
        txtpreco.setEnabled(false);
        cbCliente.setEnabled(false);
        cbDescProd.setEnabled(false);
        cbVendedor.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnBuscarProduto.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnSalvarPedido.setEnabled(false);
        btnSelecionaCliente.setEnabled(false);
        btnSelecionaVendedor.setEnabled(false);
       
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lblPedido = new javax.swing.JLabel();
        txtPedido = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        lblCodProduto = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblQtd = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnSalvarPedido = new javax.swing.JButton();
        lblTotalPedidos1 = new javax.swing.JLabel();
        lblTotalPedidos2 = new javax.swing.JLabel();
        btnSelecionaVendedor = new javax.swing.JButton();
        btnSelecionaCliente = new javax.swing.JButton();
        lblContato = new javax.swing.JLabel();
        lblContatoCliente = new javax.swing.JLabel();
        lblEndCliente = new javax.swing.JLabel();
        lblEnde = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        cbVendedor = new javax.swing.JComboBox<>();
        btnBuscarProduto = new javax.swing.JButton();
        txtCod = new javax.swing.JTextField();
        cbDescProd = new javax.swing.JComboBox<>();
        txtDesProduto = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Pedidos - Dioner Weiss");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        lblPedido.setText("Nº Pedido");

        txtPedido.setEditable(false);
        txtPedido.setText(String.valueOf(DAL.getInstancia().getUltimoPedido()));

        LocalDate hj = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtData.setText(hj.format(formatter));

        lblData.setText("Data de Emissão");

        lblCliente.setText("Cliente");

        lblVendedor.setText("Vendedor");

        lblCodProduto.setText("Cód Produto");

        lblDescricao.setText("Descrição do Produto");

        lblQtd.setText("Quant.");

        lblPreco.setText("Preço");

        txtpreco.setEditable(false);
        txtpreco.setEditable(false);

        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPedidos);

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemapedidos/images/incluir.fw.png"))); // NOI18N
        btnIncluir.setMnemonic('a');
        btnIncluir.setText("ADICIONAR PRODUTO");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemapedidos/images/excluir.fw.png"))); // NOI18N
        btnExcluir.setMnemonic('e');
        btnExcluir.setText("EXCLUIR PRODUTO");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemapedidos/images/alterar.fw.png"))); // NOI18N
        btnAlterar.setMnemonic('f');
        btnAlterar.setText("ALTERAR PRODUTO");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnSalvarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemapedidos/images/novo.fw.png"))); // NOI18N
        btnSalvarPedido.setMnemonic('s');
        btnSalvarPedido.setText("SALVAR PEDIDO");
        btnSalvarPedido.setAlignmentY(0.0F);
        btnSalvarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalvarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPedidoActionPerformed(evt);
            }
        });

        lblTotalPedidos1.setText("VALOR TOTAL DO PEDIDO");

        lblTotalPedidos2.setText("R$0,00");

        btnSelecionaVendedor.setMnemonic('v');
        btnSelecionaVendedor.setText("Procurar");
        btnSelecionaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaVendedorActionPerformed(evt);
            }
        });

        btnSelecionaCliente.setMnemonic('c');
        btnSelecionaCliente.setText("Procurar");
        btnSelecionaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaClienteActionPerformed(evt);
            }
        });

        lblContato.setText("Contato:");

        lblEnde.setText("Endereço:");

        cbCliente.setEditable(true);
        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        cbVendedor.setEditable(true);
        cbVendedor.setModel(new javax.swing.DefaultComboBoxModel<>());

        btnBuscarProduto.setMnemonic('b');
        btnBuscarProduto.setText("Buscar Produto");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        txtCod.setEditable(false);
        txtCod.setText(null);

        cbDescProd.setEditable(false);
        cbDescProd.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbDescProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDescProdActionPerformed(evt);
            }
        });

        txtDesProduto.setEditable(true);

        menu.setText("MENU");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemapedidos/images/importar.fw.png"))); // NOI18N
        jMenuItem3.setText("Importar Dados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemapedidos/images/novo2.png"))); // NOI18N
        jMenuItem1.setText("Emitir Pedido");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemapedidos/images/exportar.fw.png"))); // NOI18N
        jMenuItem2.setText("Exportar Dados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem2);

        jMenuBar1.add(menu);

        jMenu3.setText("Ajuda");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemapedidos/images/ajuda.fw.png"))); // NOI18N
        jMenuItem4.setText("Ajuda");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalPedidos1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalPedidos2)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbDescProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreco)
                            .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVendedor)
                            .addComponent(lblCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDesProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblContato)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblContatoCliente)
                                        .addGap(52, 52, 52)
                                        .addComponent(lblEnde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEndCliente)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbCliente, 0, 532, Short.MAX_VALUE)
                                            .addComponent(cbVendedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSelecionaCliente)
                                            .addComponent(btnSelecionaVendedor))))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPedido)
                    .addComponent(txtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(btnSelecionaCliente)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEnde)
                        .addComponent(lblEndCliente))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblContato)
                        .addComponent(lblContatoCliente)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVendedor)
                            .addComponent(btnSelecionaVendedor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDesProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQtd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescricao)
                            .addComponent(lblCodProduto))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarPedido)
                    .addComponent(lblTotalPedidos1)
                    .addComponent(lblTotalPedidos2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limpaTabela() {
        //tabela.removeTabela();
        
        cbCliente.removeAllItems();
        cbVendedor.removeAllItems();
        cbDescProd.removeAllItems();
        txtCod.setText("");
        txtDesProduto.setText("");
        //txtPedido.setText("");
        txtQuantidade.setText("");
        txtpreco.setText("");
        
        
    }
    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        //executa o codigo para inserir os campos na tabela, se nao conseguir mostra uma mensagem de alerta
        try {
            Produto p = new Produto();
            p.setCodProduto(Integer.parseInt(txtCod.getText()));
            p.setDescProduto(cbDescProd.getSelectedItem().toString());
            p.setQuantProduto(Integer.parseInt(txtQuantidade.getText()));
            p.setPrecoProduto(Float.parseFloat(txtpreco.getText()));
            tabela.adicionaLinha(p);
            lblTotalPedidos2.setText("R$ " + tabela.valorTotal());
        } catch(NumberFormatException ex){
//            JOptionPane.showMessageDialog(null, "Por favor preencha os campos!", "Atençao", 0);
            JOptionPane.showMessageDialog(null, "Por favor, Preencha todos os campos!", "Atençao", JOptionPane.WARNING_MESSAGE);
        }
       txtCod.setText("");
       txtQuantidade.setText("");
       txtpreco.setText("");

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(tabelaPedidos.getSelectedRow() != -1){ //-1 significa que nao esta selecionada
            tabela.removeLinha(tabelaPedidos.getSelectedRow());//pega o item selecionado
            lblTotalPedidos2.setText("R$ " + tabela.valorTotal());
        }
        

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(tabelaPedidos.getSelectedRow() != -1){
            tabela.setValueAt(txtCod.getText(), tabelaPedidos.getSelectedRow(), 0);
            tabela.setValueAt(cbDescProd.getSelectedItem(), tabelaPedidos.getSelectedRow(), 1);
            tabela.setValueAt(txtQuantidade.getText(), tabelaPedidos.getSelectedRow(), 2);
            tabela.setValueAt(txtpreco.getText(), tabelaPedidos.getSelectedRow(), 3);
            lblTotalPedidos2.setText("R$ " + tabela.valorTotal());
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //importa os arquivos do 3 arquivos para o banco de dados
   
        LeitorArquivo l = new LeitorArquivo();
            
        //l.ImportaArquivoVendedores("Vendedor.csv");
        //l.ImportaArquivoProduto("Produto.csv");
        //l.ImportaArquivoCliente("Cliente.csv");
        if(l.importaTudo("Cliente.csv", "Vendedor.csv", "Produto.csv")) {
           JOptionPane.showMessageDialog(null, "Arquivos importados com sucesso!", "Sucesso!", 1);
       } else {
           JOptionPane.showMessageDialog(null, "Nao foi possivel importar os arquivos!", "Atençao", 0);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnSelecionaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaClienteActionPerformed
        //cria o array list cl com os itens do metodo pesquisarClientes()
        ArrayList<Cliente> cl = DAL.getInstancia().pesquisarClientesCB((String) cbCliente.getSelectedItem());
        cbCliente.removeAllItems(); //remove todos os itens do combobox
        //preenche o combo box com os novos itens pesquisados
        for(int i=0; i<cl.size();i++) {
            cbCliente.addItem(cl.get(i).getNome());
            
        }
        cbCliente.showPopup();
    }//GEN-LAST:event_btnSelecionaClienteActionPerformed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        //Cliente c = DAL.getInstancia().pesquisarCliente(cbCliente.getSelectedItem().toString());
        //System.out.println(c.getCodCliente() + "  " + c.getEndereco() +"   " + c.getNome() + "  " + c.getTelefone());
        //precisa ser feito assim para evitar erro de nullExceptionPoint
        if (cbCliente.getSelectedItem() != null) { // verifica se o item selecionado no combobox nao e nulo
            //cria um novo objeto cliente
            Cliente c = DAL.getInstancia().pesquisarCliente(cbCliente.getSelectedItem().toString());
            //seta as informaçoes nos labels
            lblContatoCliente.setText(c.getTelefone());
            lblEndCliente.setText(c.getEndereco());
        } else {
            lblContatoCliente.setText("");
            lblEndCliente.setText("");
        }
        
    }//GEN-LAST:event_cbClienteActionPerformed

    private void btnSelecionaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaVendedorActionPerformed
        ArrayList<Vendedor> vl = DAL.getInstancia().pesquisarVendedorCB((String) cbVendedor.getSelectedItem());
        cbVendedor.removeAllItems();
        for(int i=0; i<vl.size();i++) {
            cbVendedor.addItem(vl.get(i).getNome());
            
        }
        cbVendedor.showPopup();
    }//GEN-LAST:event_btnSelecionaVendedorActionPerformed

    private void btnSalvarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPedidoActionPerformed
        //instacia um novo objeto Pedido
        Pedido p = new Pedido();
        try {
            p.setCodPedido(Integer.parseInt(txtPedido.getText()));

            Cliente c = DAL.getInstancia().pesquisarCliente((String) cbCliente.getSelectedItem());
            p.setCodCliente(c.getCodCliente());

            Vendedor v = DAL.getInstancia().pesquisarVendedor((String) cbVendedor.getSelectedItem());
            p.setCodVendedor(v.getCodVendedor());
            //formatacao da data

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date data;
             
             //primeiro converte a string(dd/MM/yyyy) para Date(yyyy-MM-dd)
            
                data = formato.parse(txtData.getText());
                java.sql.Date dataSql = new java.sql.Date(data.getTime());
                p.setDataEmisao(dataSql);
           
            
            //apos converte o Date do Java para o Date do MySQL
            
            
            
            if (DAL.getInstancia().inserePedido(p)) {
                //Gambiarra monstra aqui
                for (int i=tabelaPedidos.getRowCount(); i>0; i--) {
                    System.out.println(i + " " + tabelaPedidos.getRowCount());
                    tabela.insereLinha(i-1, txtPedido);
                    tabela.removeLinha(tabelaPedidos.getRowCount()-1);
                    
                    //System.out.println(ip.getCodProduto());
                }
                txtPedido.setText(String.valueOf(DAL.getInstancia().getUltimoPedido()));
                lblTotalPedidos2.setText("R$ " + tabela.valorTotal());
                //tabela.removeTabela();
                JOptionPane.showMessageDialog(null, "Pedido inserido com sucesso!", "Sucesso!", 2);
                
            } else {
                JOptionPane.showMessageDialog(null, "Pedido nao inserido!", "Atençao!", 1);
            }
            
                
                
            
             
        } catch (ParseException ex) {
             Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Por favor, Preencha todos os campos!", "Atençao", JOptionPane.WARNING_MESSAGE);
         }catch (NullPointerException e){
             JOptionPane.showMessageDialog(null, "Por favor, Preencha todos os campos!", "Atençao", JOptionPane.WARNING_MESSAGE);
         }
       
        
        //limpaTabela();
       
        
    }//GEN-LAST:event_btnSalvarPedidoActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        //falta fazer a verificaçao p != null
        
        
        ArrayList<Produto> p = DAL.getInstancia().pesquisarProdutoCB(txtDesProduto.getText());
        cbDescProd.removeAllItems();
        for (int i=0;i<p.size();i++) {
            cbDescProd.addItem(p.get(i).getDescProduto());
        }
        
        
        cbDescProd.showPopup();
        
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void cbDescProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDescProdActionPerformed
       
        
        //verifica se o item selecionado no combobox eh null
        //precisa ser feito dessa forma para evitar erro de nullExceptionPoint
        
        if (cbDescProd.getSelectedItem() != null) {
            //cria um  novo objeto p retornado pelo metodo de pesquisa pesquisarProduto() do arquivo DAL
            Produto p = DAL.getInstancia().pesquisarProduto(cbDescProd.getSelectedItem().toString());
            txtCod.setText(String.valueOf(p.getCodProduto()));
            txtpreco.setText(String.valueOf(p.getPrecoProduto()));
            //txtDesProduto.setText(p.getDescProduto());
        } 
        
        else { // se p for null, os campos ficam vazios
            txtCod.setText("");
            txtpreco.setText("");
        }
       
    }//GEN-LAST:event_cbDescProdActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ExportadorArquivo ea = new ExportadorArquivo();
       
        if((ea.ExportaPedido("Pedido.csv", DAL.getInstancia().getTodosPedidos()))&& (ea.ExportaItemPedido("ItemPedido.csv", DAL.getInstancia().getTodosItens()))) {
            JOptionPane.showMessageDialog(null, "Arquivos exportados com sucesso!", "Sucesso", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Nao foi possivel exportar os dados!", "Atencao", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ImageIcon imagem = new ImageIcon(getClass().getResource("Ajuda.jpg"));
        JOptionPane.showMessageDialog(null,"","Ajuda", JOptionPane.INFORMATION_MESSAGE,imagem);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        txtPedido.setEnabled(true);
        txtCod.setEnabled(true);
        txtData.setEnabled(true);
        txtDesProduto.setEnabled(true);
        txtQuantidade.setEnabled(true);
        txtpreco.setEnabled(true);
        cbCliente.setEnabled(true);
        cbDescProd.setEnabled(true);
        cbVendedor.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnBuscarProduto.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnIncluir.setEnabled(true);
        btnSalvarPedido.setEnabled(true);
        btnSelecionaCliente.setEnabled(true);
        btnSelecionaVendedor.setEnabled(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tabelaPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPedidosMouseClicked
        if(tabelaPedidos.getSelectedRow() != -1){ //-1 significa que nao esta selecionada
            txtCod.setText((String.valueOf(tabelaPedidos.getValueAt(tabelaPedidos.getSelectedRow(), 0))));
            txtQuantidade.setText((String.valueOf(tabelaPedidos.getValueAt(tabelaPedidos.getSelectedRow(), 2))));
            txtpreco.setText((String.valueOf(tabelaPedidos.getValueAt(tabelaPedidos.getSelectedRow(), 3))));
            
            cbDescProd.removeAllItems();
            cbDescProd.addItem((String.valueOf(tabelaPedidos.getValueAt(tabelaPedidos.getSelectedRow(), 1))));
            
            
            
        }
    }//GEN-LAST:event_tabelaPedidosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSalvarPedido;
    private javax.swing.JButton btnSelecionaCliente;
    private javax.swing.JButton btnSelecionaVendedor;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbDescProd;
    private javax.swing.JComboBox<String> cbVendedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodProduto;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblContatoCliente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEndCliente;
    private javax.swing.JLabel lblEnde;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblTotalPedidos1;
    private javax.swing.JLabel lblTotalPedidos2;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JMenu menu;
    private javax.swing.JTable tabelaPedidos;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDesProduto;
    private javax.swing.JTextField txtPedido;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtpreco;
    // End of variables declaration//GEN-END:variables
}
